name: Terraform Deploy

on:
  push:
    branches:
    - dev
    - test
    - main
    - feature/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "test" ]]; then
            echo "ENV=test" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Display Environment
        run: echo "Deploying to $ENV"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654541855:role/Role_01
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: environments/${{ env.ENV }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: environments/${{ env.ENV }}
        run: terraform init -reconfigure

      - name: Terraform Validate
        working-directory: environments/${{ env.ENV }}
        run: terraform validate

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: environments/${{ env.ENV }}
          framework: terraform
          soft_fail: true

      - name: Terraform Plan
        working-directory: environments/${{ env.ENV }}
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: environments/${{ env.ENV }}
        run: terraform apply -auto-approve -input=false
