name: Terraform Deploy

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:

    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
        - dev
        - test
        - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Selected Environment
        run: echo "Deploying to $ENV"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654541855:role/Role_01
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: environments/${{ env.ENV }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: environments/${{ env.ENV }}
        run: terraform init -reconfigure

      - name: Terraform Validate
        working-directory: environments/${{ env.ENV }}
        run: terraform validate

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: environments/${{ env.ENV }}
          framework: terraform
          soft_fail: true

      - name: Terraform Plan
        working-directory: environments/${{ env.ENV }}
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: environments/${{ env.ENV }}
        run: terraform apply -auto-approve -input=false
